config/routes.rb
Betastore::Application.routes.draw do
  resources :subscriptions
  get '/products' => 'products#index'

  namespace :admin do
    resources :products
    get  '/login' => 'logins#new'
    post '/login' => 'logins#create'
    # get '/products/new' => 'products#new', as: 'new_product'
    # get '/products/:product_id' => 'products#show', as: 'product'
    # get '/products' => 'products#index'
    # post '/products' => 'products#create'
  end

  root :to => 'subscriptions#new'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  has_many :line_items, :through => :orders
  has_many :products, :through => :line_items
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  after_save :calculate_order_total_amount
  after_destroy :calculate_order_total_amount

  def calculate_order_total_amount
    order.calculate_total_amount
  end

  def total_amount
    quantity * product.price
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :line_items
  has_many :products, :through => :line_items

  after_commit :queue_processing, on: :create

  def queue_processing
    OrderWorker.perform_async(id)
  end

  def self.recent
    where("placed_at > ?", 7.days.ago)
  end

  def self.by(customer)
    where(customer_id: customer.id)
  end

  def calculate_total_amount
    self.total_amount = 0
    for line_item in line_items
      self.total_amount += line_item.total_amount
    end
    save
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, :through => :line_items

  validates :name, presence: { message: 'is required' }
  validates :price, numericality: { greater_than_or_equal_to: 0,
    message: 'must be a number' }

  def send_confirmation_email
    # TODO: Actually send email
    logger.warn "Sending emai to #{email}"
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password validations: false
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_login
end

app/controllers/admin/logins_controller.rb
class Admin::LoginsController < Admin::BaseController
  layout 'login'

  skip_before_action :require_login

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_products_path
    else
      flash.now[:danger] = 'Log In Failed'
      render 'new'
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  def index
    @products = Product.order('name')
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product), notice: "Product #{@product.id} was created"
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: "Product #{@product.id} was updated"
    else
      render 'new'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to admin_products_path, notice: "Product #{@product.id} was deleted"
    else
      render 'show'
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :image_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def logged_in?
    session[:user_id].present?
  end

  def require_login
    unless logged_in?
      redirect_to admin_login_path, alert: 'Please log in to continue'
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order('name')
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)

    if @subscription.save
      redirect_to new_subscription_path, notice: 'Subscription was successfully created.'
    else
      render action: 'new'
    end
  end

  private
  def subscription_params
    params.require(:subscription).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/admin/logins/new.html.erb
<div class="jumbotron">
  <%= form_tag admin_login_path, class: 'form-horizontal', role: 'form' do %>

    <div class="form-group">
      <%= label_tag :email, nil, class: 'col-sm-2 control-label' %>
      <div class="col-sm-4">
        <%= email_field_tag :email, params[:email], class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :password, nil, class: 'col-sm-2 control-label' %>
      <div class="col-sm-4">
        <%= password_field_tag :password, nil, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-4">
        <%= submit_tag "Log In", class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/products/_form.html.erb
<div class="row">
  <% if @product.errors.present? %>
    <div class="alert alert-danger">
      <ul>
        <% for error in @product.errors.full_messages %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for [:admin, @product], { html: { role: 'form' } } do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :image_url %>
      <%= f.url_field :image_url, class: 'form-control' %>
    </div>

    <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/admin/products/edit.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Products", admin_products_path %></li>
  <li><%= link_to "Product ##{@product.id}", admin_product_path(@product) %></li>
  <li class="active">Edit Product</li>
</ol>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<h1>Products</h1>

<div class="row">
  <div class="col-md-1 col-md-offset-11" style="margin-bottom: 15px">
    <%= link_to "New Product", new_admin_product_path, class: 'btn btn-primary' %>
  </div>
</div>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Created At</th>
  </tr>
  <% for product in @products %>
    <tr>
      <td><%= link_to product.name, admin_product_path(product) %></td>
      <td><%= number_to_currency product.price %></td>
      <td><%= product.created_at.strftime('%a %b %e %Y, %I:%M %p') %></td>
    </tr>
  <% end %>
</table>

app/views/admin/products/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Products", admin_products_path %></li>
  <li class="active">New Product</li>
</ol>

<%= render 'form' %>

app/views/admin/products/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Products", admin_products_path %></li>
  <li class="active">Product #<%= @product.id %></li>
</ol>

<div class="row">
  <h1><%= @product.name %></h1>
  <%= image_tag @product.image_url, class: "img-responsive" %>
  <p><%= number_to_currency @product.price %></p>
</div>

<div class="row">
  <%= link_to "Edit", edit_admin_product_path(@product),
                        class: 'btn btn-primary' %>

  <%= link_to "Delete", admin_product_path(@product),
                        class: 'btn btn-danger',
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="#">
        <%= image_tag "logo.jpg", height: 50 %>
      </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active">
        <%= link_to "Products", admin_products_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Betastore</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/nav' %>
      <% if flash[:notice].present? %>
        <div class="row">
          <div class="alert alert-success"><%= flash[:notice] %></div>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Betastore</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <% if flash[:notice].present? %>
        <div class="row">
          <div class="alert alert-success"><%= flash[:notice] %></div>
        </div>
      <% end %>
      <% if flash[:danger].present? %>
        <div class="row">
          <div class="alert alert-danger"><%= flash[:danger] %></div>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<h1>This is a list of products</h1>
<ul>
  <% for product in @products %>
    <li><%= product.name %></li>
  <% end %>
</ul>

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %>
        prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, "Let me know when you launch:" %>
    <%= f.text_field :email %>
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

<% if flash.present? %>
  <% flash.each do |k,v| %>
    <div class="<%= k %>"><%= v %></div>
  <% end %>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.email %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<%= render 'form' %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>